export type AssociadoBeneficiadoType = {
  nome: string;
  email: string;
  telefone: string;
  cpf: string;
  documentoIdentidade?: string;
  dataNascimento: string;
  endereco: string;
  cidade: string;
  estado: string;
  nomeConcessionaria: string;
  consumoMedio: string;
  planoDesejado: string;
  aceitaTermos: boolean;
  observacoes: string;
  interesseCompartilhar: string;
};
export type BeneficiadoType = {
  nome: string;
  email: string;
  telefone: string;
  cpf: string;
  documentoIdentidade: string;
  dataNascimento: string;
  endereco: string;
  cidade: string;
  estado: string;
  nomeConcessionaria: string;
  consumoMedio: string;
  planoDesejado: string;
  aceitaTermos: boolean;
  observacoes: string;
};
